### ISSUE TITLE
Error while building Debian package

### ISSUE THREAD

**Issue by Paccos** [openbase/bco#8]
<pre>[ERROR] Failed to create debian package /home/ppekala/workspace/openbase/bco/target/bco_1.6.0~20180420153740_all.deb
org.vafer.jdeb.PackagingException: Failed to create debian package /home/ppekala/workspace/openbase/bco/target/bco_1.6.0~20180420153740_all.deb
	at org.vafer.jdeb.DebMaker.makeDeb(DebMaker.java:348)
	at org.vafer.jdeb.maven.DebMojo.execute(DebMojo.java:583)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.vafer.jdeb.PackagingException: Could not create deb package
	at org.vafer.jdeb.DebMaker.createSignedDeb(DebMaker.java:573)
	at org.vafer.jdeb.DebMaker.createDeb(DebMaker.java:463)
	at org.vafer.jdeb.DebMaker.makeDeb(DebMaker.java:344)
	... 23 more
Caused by: java.io.FileNotFoundException: Data source not found : /home/ppekala/workspace/openbase/bco/target/appassembler/share/bco/lib
	at org.vafer.jdeb.maven.Data.produce(Data.java:189)
	at org.vafer.jdeb.DataBuilder.buildData(DataBuilder.java:265)
	at org.vafer.jdeb.DebMaker.createSignedDeb(DebMaker.java:489)
	... 25 more
[ERROR] Failed to execute goal org.vafer:jdeb:1.6:jdeb (default) on project bco: Failed to create debian package /home/ppekala/workspace/openbase/bco/target/bco_1.6.0~20180420153740_all.deb: Could not create deb package: Data source not found : /home/ppekala/workspace/openbase/bco/target/appassembler/share/bco/lib -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
</pre>

**Comment by DivineThreepwood** [comment]
debian packages not supported any longer.
