### ISSUE TITLE
AbstractEnergySavingAgent causes Deadlock as follows

### ISSUE THREAD

**Issue by DivineThreepwood** [openbase/bco#84]
```
00:10:00.784 [pool-2-thread-10] INFO  o.o.b.d.c.l.u.l.LocationControllerImpl Hell is updated from unknown to absent.
00:10:00.789 [pool-1-thread-69] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry [AgentConfigRegistry]: Register UnitConfig[Absence_Energy_Saving_Agent_Unit_Test:Absence_Energy_Saving_Agent_Unit_Test]...
00:10:00.797 [pool-1-thread-69] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry [AgentConfigRegistry]: 12% of max consistency checks passed of AgentConfigRegistry after 1 applied modifications.
00:10:00.801 [pool-1-thread-69] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry [AgentConfigRegistry]: 100% consistency checks passed of AgentConfigRegistry after 8 applied modifications.
00:10:00.805 [pool-1-thread-69] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry [LocationConfigRegistry]: 100% consistency checks passed of LocationConfigRegistry after 2 applied modifications.
00:10:00.811 [pool-1-thread-69] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry [UserConfigRegistry]: Register UnitConfig[user-absence_energy_saving_agent_unit_test_stairway_to_heaven-b145e36b]...
00:10:00.826 [pool-1-thread-69] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry [UserConfigRegistry]: 100% consistency checks passed of UserConfigRegistry after 11 applied modifications.
00:10:00.828 [pool-1-thread-69] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry [LocationConfigRegistry]: 100% consistency checks passed of LocationConfigRegistry after 1 applied modifications.
00:10:00.834 [pool-1-thread-69] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry [AuthorizationGroupConfigRegistry]: 100% consistency checks passed of AuthorizationGroupConfigRegistry after 1 applied modifications.
00:10:00.862 [pool-1-thread-69] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry [LocationConfigRegistry]: Update UnitConfig[Location-3:Stairway to Heaven]...
00:10:01.028 [pool-1-thread-69] INFO  o.o.b.d.c.l.u.UnitControllerRegistrySynchronizer 2 changes synchronized.
00:10:01.126 [pool-1-thread-48] INFO  o.o.b.a.p.a.AbsenceEnergySavingAgent deactivationTriggerPoolObserver current UNKNOWN trigger: UNKNOWN
00:10:01.128 [pool-1-thread-48] INFO  o.o.b.a.p.a.AbsenceEnergySavingAgent Absence Energy Saving Agent Unit Test is updated from unknown to inactive.
00:10:01.131 [pool-1-thread-48] INFO  o.o.b.d.c.a.ActionImpl BCO changed activation of Absence Energy Saving Agent Unit Test to inactive.
00:10:01.140 [pool-1-thread-78] INFO  o.o.b.d.c.l.u.UnitControllerRegistrySynchronizer 1 changes synchronized.
00:10:01.143 [pool-1-thread-48] INFO  o.o.b.a.p.a.AbsenceEnergySavingAgent Absence Energy Saving Agent Unit Test is updated from inactive to active.
00:10:01.146 [pool-1-thread-48] INFO  o.o.b.a.p.a.AbsenceEnergySavingAgent deactivationTriggerPoolObserver current ACTIVE trigger: INACTIVE
00:10:01.146 [pool-1-thread-48] INFO  o.o.b.d.c.a.ActionImpl BCO changed activation of Absence Energy Saving Agent Unit Test to active.
00:10:01.154 [pool-2-thread-10] INFO  o.o.b.a.p.a.AbsenceEnergySavingAgent Analyze AbsenceEnergySavingAgent[AGENT[Absence Energy Saving Agent Unit Test]] which currently generates 1.0 events per hour which is 0.0% of the totally allowed ones.
00:10:01.185 [pool-1-thread-68] INFO  o.o.b.d.c.l.u.ColorableLightController PH Hue E27 Device Stairway is updated from off to off.
00:10:01.190 [pool-1-thread-68] INFO  o.o.b.d.c.a.ActionImpl Absence Energy Saving Agent Unit Test@Stairway to Heaven changed power of PH Hue E27 Device Stairway to off.
testAbsenceEnergySavingAgent
00:10:03.018 [Test worker] INFO  o.o.b.d.c.l.u.MotionDetectorController F Motion Sensor Device Stairway is updated from unknown to motion.
00:10:03.020 [Test worker] INFO  o.o.b.d.r.l.u.u.UnitStateAwaiter Waiting because unit data not available!
00:10:03.038 [Test worker] INFO  o.o.b.d.r.l.u.u.UnitStateAwaiter Woke up! Time waited 16ms
00:10:03.038 [Test worker] INFO  o.o.b.d.r.l.u.u.UnitStateAwaiter State not yet reached. Stairway to Heaven still in state [Stairway to Heaven changed standby of Stairway to Heaven to standby state service, 1668467400581, value=running.] Waiting...
00:10:03.055 [pool-1-thread-66] INFO  o.o.b.d.c.l.u.l.LocationControllerImpl Stairway to Heaven is updated from absent to present.
00:10:03.068 [pool-1-thread-29] INFO  o.o.b.d.c.l.u.l.LocationControllerImpl Paradise is updated from absent to present.
00:10:03.093 [Test worker] INFO  o.o.b.d.r.l.u.u.UnitStateAwaiter Woke up! Time waited 55ms
00:10:04.110 [pool-1-thread-83] WARN  o.o.b.d.r.l.u.ColorableLightRemote Remote connection to Controller[/location-1/location-3/colorablelight/colorablelight-3] lost!
00:10:04.115 [pool-1-thread-97] ERROR o.o.b.d.c.a.ActionImpl Can not finalize ActionImpl[action-termination-economy-994fa6b6|POWER_STATE_SERVICE|{"value": "OFF"}|colorablelight-8efc27b4|user-bco-99618d46(SYSTEM)|ABORTING] it seems the execution has stuck.
00:10:04.122 [pool-1-thread-97] WARN  o.o.b.d.c.a.ActionImpl Thread[pool-1-thread-66] state[TIMED_WAITING]
=== Stacktrace ===
java.base@17.0.5/jdk.internal.misc.Unsafe.park(Native Method)
java.base@17.0.5/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252)
java.base@17.0.5/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:717)
java.base@17.0.5/java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireNanos(AbstractQueuedSynchronizer.java:986)
java.base@17.0.5/java.util.concurrent.locks.ReentrantReadWriteLock$WriteLock.tryLock(ReentrantReadWriteLock.java:1131)
app//org.openbase.jul.extension.protobuf.BuilderSyncSetup.tryLockWrite(BuilderSyncSetup.java:175)
app//org.openbase.bco.dal.control.layer.unit.AbstractUnitController.applyDataUpdate(AbstractUnitController.java:1372)
app//org.openbase.bco.dal.lib.layer.unit.UnitController.applyDataUpdate(UnitController.java:79)
app//org.openbase.bco.dal.lib.layer.unit.UnitController.applyServiceState(UnitController.java:120)
app//org.openbase.bco.dal.lib.layer.unit.UnitController.applyServiceState(UnitController.java:99)
app//org.openbase.bco.dal.lib.layer.unit.UnitController.applyServiceState(UnitController.java:141)
app//org.openbase.bco.dal.lib.layer.service.mock.OperationServiceFactoryMock.update(OperationServiceFactoryMock.java:261)
app//org.openbase.bco.dal.lib.layer.service.mock.OperationServiceFactoryMock$PowerStateOperationServiceMock.setPowerState(OperationServiceFactoryMock.java:168)
java.base@17.0.5/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
java.base@17.0.5/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
java.base@17.0.5/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.base@17.0.5/java.lang.reflect.Method.invoke(Method.java:568)
app//org.openbase.bco.dal.lib.layer.service.Services.invokeServiceMethod(Services.java:546)
app//org.openbase.bco.dal.lib.layer.service.Services.invokeServiceMethod(Services.java:522)
app//org.openbase.bco.dal.lib.layer.service.Services.invokeOperationServiceMethod(Services.java:569)
app//org.openbase.bco.dal.control.layer.unit.AbstractUnitController.performOperationService(AbstractUnitController.java:1993)
app//org.openbase.bco.dal.control.action.ActionImpl.lambda$execute$0(ActionImpl.java:303)
app//org.openbase.bco.dal.control.action.ActionImpl$$Lambda$679/0x000000080133e150.call(Unknown Source)
java.base@17.0.5/java.util.concurrent.FutureTask.run(FutureTask.java:264)
java.base@17.0.5/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
java.base@17.0.5/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
java.base@17.0.5/java.lang.Thread.run(Thread.java:833)
==================
00:10:04.123 [pool-1-thread-97] WARN  o.o.b.d.c.a.ActionImpl Thread[pool-1-thread-97] state[RUNNABLE]
=== Stacktrace ===
java.base@17.0.5/java.lang.Thread.dumpThreads(Native Method)
java.base@17.0.5/java.lang.Thread.getAllStackTraces(Thread.java:1662)
app//org.openbase.jul.exception.StackTracePrinter.printAllStackTraces(StackTracePrinter.java:145)
app//org.openbase.bco.dal.control.action.ActionImpl.cancelActionTask(ActionImpl.java:737)
app//org.openbase.bco.dal.control.action.ActionImpl.abort(ActionImpl.java:573)
app//org.openbase.bco.dal.lib.action.SchedulableAction.abort(SchedulableAction.java:64)
app//org.openbase.bco.dal.control.layer.unit.AbstractUnitController.reschedule(AbstractUnitController.java:1080)
app//org.openbase.bco.dal.control.layer.unit.AbstractUnitController.scheduleAction(AbstractUnitController.java:858)
app//org.openbase.bco.dal.control.layer.unit.AbstractUnitController.applyAction(AbstractUnitController.java:675)
app//org.openbase.bco.dal.control.layer.unit.AbstractUnitController.internalApplyActionAuthenticated(AbstractUnitController.java:1278)
app//org.openbase.bco.dal.control.layer.unit.AbstractUnitController.lambda$applyActionAuthenticated$5(AbstractUnitController.java:1226)
app//org.openbase.bco.dal.control.layer.unit.AbstractUnitController$$Lambda$732/0x0000000801487680.process(Unknown Source)
app//org.openbase.bco.authentication.lib.AuthenticatedServiceProcessor.authenticatedAction(AuthenticatedServiceProcessor.java:135)
app//org.openbase.bco.authentication.lib.AuthenticatedServiceProcessor.authenticatedAction(AuthenticatedServiceProcessor.java:90)
app//org.openbase.bco.authentication.lib.AuthenticatedServiceProcessor.authenticatedAction(AuthenticatedServiceProcessor.java:69)
app//org.openbase.bco.dal.control.layer.unit.AbstractUnitController.applyActionAuthenticated(AbstractUnitController.java:1244)
java.base@17.0.5/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
java.base@17.0.5/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
java.base@17.0.5/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.base@17.0.5/java.lang.reflect.Method.invoke(Method.java:568)
app//kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97)
app//kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Instance.call(CallerImpl.kt:113)
app//kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:108)
app//org.openbase.jul.communication.mqtt.RPCMethod.invoke(RPCMethod.kt:223)
app//org.openbase.jul.communication.mqtt.RPCServerImpl.handleRemoteCall(RPCServerImpl.kt:141)
app//org.openbase.jul.communication.mqtt.RPCServerImpl.activate$lambda-2$lambda-1(RPCServerImpl.kt:65)
app//org.openbase.jul.communication.mqtt.RPCServerImpl$$Lambda$552/0x0000000801130aa0.accept(Unknown Source)
app//com.hivemq.client.internal.mqtt.MqttAsyncClient$CallbackSubscriber.onNext(MqttAsyncClient.java:303)
app//com.hivemq.client.internal.mqtt.MqttAsyncClient$CallbackSubscriber.onNext(MqttAsyncClient.java:288)
app//com.hivemq.client.rx.FlowableWithSingle$SingleFutureSubscriber.onNext(FlowableWithSingle.java:406)
app//com.hivemq.client.internal.rx.operators.FlowableWithSingleCombine$SplitSubscriber$Default.tryOnNextActual(FlowableWithSingleCombine.java:235)
app//com.hivemq.client.internal.rx.operators.FlowableWithSingleCombine$SplitSubscriber.tryOnNext(FlowableWithSingleCombine.java:200)
app//io.reactivex.internal.operators.flowable.FlowableObserveOn$ObserveOnConditionalSubscriber.runAsync(FlowableObserveOn.java:649)
app//io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:176)
app//io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:288)
app//io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:253)
java.base@17.0.5/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
java.base@17.0.5/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
java.base@17.0.5/java.lang.Thread.run(Thread.java:833)
==================
00:10:04.127 [pool-1-thread-66] INFO  o.o.b.d.c.l.u.ColorableLightController PH Hue E27 Device Stairway is updated from off to off.
00:10:04.183 [pool-1-thread-94] INFO  o.o.b.d.c.l.u.ColorableLightController PH Hue E27 Device Stairway is updated from off to off.
00:10:04.184 [pool-1-thread-94] INFO  o.o.b.d.c.a.ActionImpl BCO changed power of PH Hue E27 Device Stairway to off.
00:10:04.223 [pool-1-thread-83] INFO  o.o.b.d.r.l.u.ColorableLightRemote Connection reestablished ColorableLightRemote[scope:/location-1/location-3/colorablelight/colorablelight-3]
00:10:04.252 [pool-1-thread-60] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry [AgentConfigRegistry]: Remove UnitConfig[Agent-1:Absence Energy Saving Agent Unit Test]...
00:10:04.252 [pool-1-thread-60] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry [UserConfigRegistry]: Remove UnitConfig[User-5:Absence Energy Saving Agent Unit Test@Stairway to Heaven]...
00:10:04.257 [pool-1-thread-60] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry [LocationConfigRegistry]: 100% consistency checks passed of LocationConfigRegistry after 1 applied modifications.
00:10:04.265 [pool-1-thread-60] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry [AuthorizationGroupConfigRegistry]: 100% consistency checks passed of AuthorizationGroupConfigRegistry after 1 applied modifications.
00:10:04.272 [pool-1-thread-60] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry [LocationConfigRegistry]: 100% consistency checks passed of LocationConfigRegistry after 2 applied modifications.
00:10:04.304 [Test worker] INFO  o.o.a.t.a.AbstractBCOAgentManagerTest Cancel all ongoing actions...
00:10:04.343 [Test worker] INFO  o.o.b.d.t.AbstractBCOTest Cancel 1 ongoing test action ...

org.openbase.jul.exception.CouldNotPerformException
	at app//org.openbase.bco.dal.remote.action.RemoteAction.waitForRegistration(RemoteAction.java:1121)
	at app//org.openbase.bco.dal.remote.action.RemoteAction.waitForRegistration(RemoteAction.java:1129)
	at app//org.openbase.bco.dal.remote.action.RemoteAction.waitForActionState(RemoteAction.java:992)
	at app//org.openbase.bco.dal.remote.action.RemoteAction.waitForActionState(RemoteAction.java:973)
	at app//org.openbase.bco.dal.test.AbstractBCOTest.waitForExecution(AbstractBCOTest.java:217)
	at app//org.openbase.bco.app.preset.agent.AbsenceEnergySavingAgentTest.testAbsenceEnergySavingAgent(AbsenceEnergySavingAgentTest.java:110)
	at java.base@17.0.5/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@17.0.5/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base@17.0.5/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@17.0.5/java.lang.reflect.Method.invoke(Method.java:568)
	at app//org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
	at app//org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at app//org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at app//org.junit.jupiter.engine.extension.TimeoutInvocation.proceed(TimeoutInvocation.java:46)
	at app//org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at app//org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at app//org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at app//org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at app//org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at app//org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at app//org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at app//org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at app//org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at app//org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at app//org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at app//org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:214)
	at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at app//org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:210)
	at app//org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:135)
	at app//org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:66)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at app//org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base@17.0.5/java.util.ArrayList.forEach(ArrayList.java:1511)
	at app//org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at app//org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base@17.0.5/java.util.ArrayList.forEach(ArrayList.java:1511)
	at app//org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at app//org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at app//org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at app//org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at app//org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:99)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:79)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:75)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
	at java.base@17.0.5/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@17.0.5/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base@17.0.5/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@17.0.5/java.lang.reflect.Method.invoke(Method.java:568)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at jdk.proxy1/jdk.proxy1.$Proxy2.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$3.run(TestWorker.java:193)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:133)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:71)
	at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
```

**Comment by DivineThreepwood** [comment]
Has been fixed by #88
